[env:cardputer_adv]
platform = espressif32
board = m5stack-stamps3
framework = arduino


monitor_speed = 115200
upload_speed = 921600

board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.partitions = huge_app.csv

build_unflags =
  -std=gnu++11
  -std=c++11

build_flags =
  -std=gnu++17
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MSC_ON_BOOT=0
  -D ARDUINO_USB_DFU_ON_BOOT=0

lib_deps =
  m5stack/M5Cardputer
  adafruit/Adafruit NeoPixel @ ^1.12.0